import AppKit
import ApplicationServices
import Foundation

@MainActor
final class TextInsertionController {
    enum InsertionResult: Equatable {
        case insertedDirectly
        case sentPasteShortcut
        case copied
    }

    struct PermissionHealth: Equatable {
        let accessibilityEnabled: Bool
        let eventPostingEnabled: Bool

        var canAutoInsert: Bool {
            accessibilityEnabled || eventPostingEnabled
        }

        var summary: String {
            let accessibilityStatus = accessibilityEnabled ? "Accessibility on" : "Accessibility off"
            let eventStatus = eventPostingEnabled ? "Input Monitoring on" : "Input Monitoring off"
            return "\(accessibilityStatus), \(eventStatus)"
        }
    }

    enum InsertionMode: String, CaseIterable, Identifiable {
        case automatic
        case pasteCommandOnly

        var id: String { rawValue }

        var label: String {
            switch self {
            case .automatic:
                return "Automatic"
            case .pasteCommandOnly:
                return "Paste Command Only"
            }
        }

        var description: String {
            switch self {
            case .automatic:
                return "Try direct Accessibility insertion first, then fall back to clipboard paste."
            case .pasteCommandOnly:
                return "Use clipboard paste only. This is closest to most dictation apps."
            }
        }
    }

    private let pasteboard = NSPasteboard.general
    private let focusedApplicationAttribute = kAXFocusedApplicationAttribute as CFString
    private let focusedElementAttribute = "AXFocusedUIElement" as CFString
    private let selectedTextRangeAttribute = "AXSelectedTextRange" as CFString
    private let valueAttribute = "AXValue" as CFString
    private let transientPasteboardTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]
    private var restoreTask: Task<Void, Never>?
    var insertionMode: InsertionMode = .automatic
    var shouldPreserveClipboard: Bool = true

    var permissionHealth: PermissionHealth {
        PermissionHealth(
            accessibilityEnabled: AXIsProcessTrusted(),
            eventPostingEnabled: CGPreflightPostEventAccess()
        )
    }

    var hasPastePermission: Bool {
        permissionHealth.canAutoInsert
    }

    var permissionSummary: String {
        permissionHealth.summary
    }

    func insert(_ text: String) async -> InsertionResult {
        let trimmedText = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedText.isEmpty else {
            return .copied
        }

        if insertionMode == .automatic,
           AXIsProcessTrusted(),
           insertUsingAccessibility(trimmedText) {
            return .insertedDirectly
        }

        guard let pendingRestore = writeTranscriptToPasteboard(trimmedText) else {
            return .copied
        }

        try? await Task.sleep(nanoseconds: 80_000_000)
        postCommandV()
        if shouldPreserveClipboard {
            schedulePasteboardRestore(pendingRestore)
        }
        return .sentPasteShortcut
    }

    func requestPastePermissionPrompt() {
        let options = [
            "AXTrustedCheckOptionPrompt": true
        ] as CFDictionary

        AXIsProcessTrustedWithOptions(options)
        CGRequestPostEventAccess()
    }

    private func insertUsingAccessibility(_ text: String) -> Bool {
        guard let focusedElement else {
            return false
        }

        return replaceFocusedElementValue(focusedElement, with: text)
    }

    private var focusedElement: AXUIElement? {
        let systemWide = AXUIElementCreateSystemWide()
        var focusedApplicationValue: CFTypeRef?
        let appResult = AXUIElementCopyAttributeValue(
            systemWide,
            focusedApplicationAttribute,
            &focusedApplicationValue
        )
        guard appResult == .success,
              let focusedApplication = axElement(from: focusedApplicationValue) else {
            return nil
        }

        var focusedElementValue: CFTypeRef?
        let elementResult = AXUIElementCopyAttributeValue(
            focusedApplication,
            focusedElementAttribute,
            &focusedElementValue
        )
        guard elementResult == .success,
              let focusedElement = axElement(from: focusedElementValue) else {
            return nil
        }

        return focusedElement
    }

    private func replaceFocusedElementValue(_ element: AXUIElement, with text: String) -> Bool {
        var valueIsSettable = DarwinBoolean(false)
        guard AXUIElementIsAttributeSettable(element, valueAttribute, &valueIsSettable) == .success,
              valueIsSettable.boolValue else {
            return false
        }

        var valueRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, valueAttribute, &valueRef) == .success,
              let currentValue = valueRef as? String else {
            return false
        }

        let selectedRange = selectedRange(in: element) ?? CFRange(location: currentValue.utf16.count, length: 0)
        guard let range = stringRange(from: selectedRange, in: currentValue) else {
            return false
        }

        let nextValue = currentValue.replacingCharacters(in: range, with: text)
        guard AXUIElementSetAttributeValue(element, valueAttribute, nextValue as CFString) == .success else {
            return false
        }

        var cursorRange = CFRange(location: selectedRange.location + text.utf16.count, length: 0)
        if let cursorValue = AXValueCreate(.cfRange, &cursorRange) {
            AXUIElementSetAttributeValue(element, selectedTextRangeAttribute, cursorValue)
        }

        return true
    }

    private func selectedRange(in element: AXUIElement) -> CFRange? {
        var rangeRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, selectedTextRangeAttribute, &rangeRef) == .success,
              let rangeValue = rangeRef,
              CFGetTypeID(rangeValue) == AXValueGetTypeID() else {
            return nil
        }

        let axValue = rangeValue as! AXValue
        guard AXValueGetType(axValue) == .cfRange else {
            return nil
        }

        var range = CFRange()
        guard AXValueGetValue(axValue, .cfRange, &range) else {
            return nil
        }

        return range
    }

    private func axElement(from value: CFTypeRef?) -> AXUIElement? {
        guard let value,
              CFGetTypeID(value) == AXUIElementGetTypeID() else {
            return nil
        }

        return (value as! AXUIElement)
    }

    private func stringRange(from cfRange: CFRange, in string: String) -> Range<String.Index>? {
        guard cfRange.location >= 0,
              cfRange.length >= 0 else {
            return nil
        }

        let utf16 = string.utf16
        guard let utf16Start = utf16.index(
            utf16.startIndex,
            offsetBy: cfRange.location,
            limitedBy: utf16.endIndex
        ),
              let utf16End = utf16.index(
                utf16Start,
                offsetBy: cfRange.length,
                limitedBy: utf16.endIndex
              ),
              let start = String.Index(utf16Start, within: string),
              let end = String.Index(utf16End, within: string) else {
            return nil
        }

        return start..<end
    }

    private func postCommandV() {
        let keyCodeForV = CGKeyCode(9)
        let source = CGEventSource(stateID: .hidSystemState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCodeForV, keyDown: true)
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCodeForV, keyDown: false)

        keyDown?.flags = .maskCommand
        keyUp?.flags = .maskCommand

        keyDown?.post(tap: .cgSessionEventTap)
        keyUp?.post(tap: .cgSessionEventTap)
    }

    private func writeTranscriptToPasteboard(_ text: String) -> PendingPasteboardRestore? {
        let snapshot = PasteboardSnapshot(pasteboard: pasteboard)
        let textToPaste = textWithNaturalTrailingSpace(text)
        let pasteboardTypes = [NSPasteboard.PasteboardType.string] + transientPasteboardTypes

        pasteboard.declareTypes(pasteboardTypes, owner: nil)
        let wroteText = pasteboard.setString(textToPaste, forType: .string)
        transientPasteboardTypes.forEach { pasteboard.setString("", forType: $0) }

        guard wroteText else {
            return nil
        }

        return PendingPasteboardRestore(
            snapshot: snapshot,
            expectedChangeCount: pasteboard.changeCount,
            writtenText: textToPaste
        )
    }

    private func schedulePasteboardRestore(_ pendingRestore: PendingPasteboardRestore) {
        restoreTask?.cancel()
        restoreTask = Task { @MainActor in
            try? await Task.sleep(nanoseconds: 10_000_000_000)
            guard !Task.isCancelled else {
                return
            }

            let currentString = pasteboard.string(forType: .string)
            guard pasteboard.changeCount == pendingRestore.expectedChangeCount ||
                    currentString == pendingRestore.writtenText else {
                return
            }

            pendingRestore.snapshot.restore(to: pasteboard)
        }
    }

    private func textWithNaturalTrailingSpace(_ text: String) -> String {
        guard let lastCharacter = text.last,
              ".!?".contains(lastCharacter) else {
            return text
        }

        return text + " "
    }
}

private struct PendingPasteboardRestore {
    let snapshot: PasteboardSnapshot
    let expectedChangeCount: Int
    let writtenText: String
}

private struct PasteboardSnapshot {
    private let items: [PasteboardItemSnapshot]

    init(pasteboard: NSPasteboard) {
        items = pasteboard.pasteboardItems?.map(PasteboardItemSnapshot.init(item:)) ?? []
    }

    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else {
            return
        }

        pasteboard.writeObjects(items.map(\.item))
    }
}

private struct PasteboardItemSnapshot {
    private let values: [(type: NSPasteboard.PasteboardType, data: Data)]

    init(item: NSPasteboardItem) {
        values = item.types.compactMap { type in
            guard let data = item.data(forType: type) else {
                return nil
            }

            return (type, data)
        }
    }

    var item: NSPasteboardItem {
        let item = NSPasteboardItem()
        values.forEach { item.setData($0.data, forType: $0.type) }
        return item
    }
}
